## Kenn Machado
## AIML-B2
## Roll no:39
## Date 26/02/2026

In [4]:
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.neural_network import MLPClassifier 
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score,recall_score,f1_score,roc_auc_score,classification_report

## load real database

In [6]:
data = load_breast_cancer()

x= data.data
y= data.target

print("Classes:",data.target_names)
#maligant, begin 
#split data 
X_train, X_test, y_train, y_test = train_test_split(x,y,test_size = 0.3)

Classes: ['malignant' 'benign']

In [10]:
data.data.shape

(569, 30)

In [15]:
import pandas as pd
df = pd.DataFrame(data.data)

In [22]:
df.shape

(569, 30)

In [31]:
df.head()

,0,1,2,3,4,5,6,7,8,9,...,20,21,22,23,24,25,26,27,28,29
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,0.07871,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,0.05667,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,0.05999,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,0.09744,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,0.05883,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [30]:
df.tail()

,0,1,2,3,4,5,6,7,8,9,...,20,21,22,23,24,25,26,27,28,29
564,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,0.1726,0.05623,...,25.450,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115
565,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,0.1752,0.05533,...,23.690,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637
566,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,0.1590,0.05648,...,18.980,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820
567,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,0.2397,0.07016,...,25.740,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400
568,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,0.1587,0.05884,...,9.456,30.37,59.16,268.6,0.08996,0.06444,0.0000,0.0000,0.2871,0.07039

In [20]:
df.isnull().sum()

0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
11    0
12    0
13    0
14    0
15    0
16    0
17    0
18    0
19    0
20    0
21    0
22    0
23    0
24    0
25    0
26    0
27    0
28    0
29    0
dtype: int64

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 30 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       569 non-null    float64
 1   1       569 non-null    float64
 2   2       569 non-null    float64
 3   3       569 non-null    float64
 4   4       569 non-null    float64
 5   5       569 non-null    float64
 6   6       569 non-null    float64
 7   7       569 non-null    float64
 8   8       569 non-null    float64
 9   9       569 non-null    float64
 10  10      569 non-null    float64
 11  11      569 non-null    float64
 12  12      569 non-null    float64
 13  13      569 non-null    float64
 14  14      569 non-null    float64
 15  15      569 non-null    float64
 16  16      569 non-null    float64
 17  17      569 non-null    float64
 18  18      569 non-null    float64
 19  19      569 non-null    float64
 20  20      569 non-null    float64
 21  21      569 non-null    float64
 22  22      569 non-null    float64
 23  23      569 non-null    float64
 24  24      569 non-null    float64
 25  25      569 non-null    float64
 26  26      569 non-null    float64
 27  27      569 non-null    float64
 28  28      569 non-null    float64
 29  29      569 non-null    float64
dtypes: float64(30)
memory usage: 133.5 KB

In [29]:
df.describe()

,0,1,2,3,4,5,6,7,8,9,...,20,21,22,23,24,25,26,27,28,29
count,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,...,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000
mean,14.127292,19.289649,91.969033,654.889104,0.096360,0.104341,0.088799,0.048919,0.181162,0.062798,...,16.269190,25.677223,107.261213,880.583128,0.132369,0.254265,0.272188,0.114606,0.290076,0.083946
std,3.524049,4.301036,24.298981,351.914129,0.014064,0.052813,0.079720,0.038803,0.027414,0.007060,...,4.833242,6.146258,33.602542,569.356993,0.022832,0.157336,0.208624,0.065732,0.061867,0.018061
min,6.981000,9.710000,43.790000,143.500000,0.052630,0.019380,0.000000,0.000000,0.106000,0.049960,...,7.930000,12.020000,50.410000,185.200000,0.071170,0.027290,0.000000,0.000000,0.156500,0.055040
25%,11.700000,16.170000,75.170000,420.300000,0.086370,0.064920,0.029560,0.020310,0.161900,0.057700,...,13.010000,21.080000,84.110000,515.300000,0.116600,0.147200,0.114500,0.064930,0.250400,0.071460
50%,13.370000,18.840000,86.240000,551.100000,0.095870,0.092630,0.061540,0.033500,0.179200,0.061540,...,14.970000,25.410000,97.660000,686.500000,0.131300,0.211900,0.226700,0.099930,0.282200,0.080040
75%,15.780000,21.800000,104.100000,782.700000,0.105300,0.130400,0.130700,0.074000,0.195700,0.066120,...,18.790000,29.720000,125.400000,1084.000000,0.146000,0.339100,0.382900,0.161400,0.317900,0.092080
max,28.110000,39.280000,188.500000,2501.000000,0.163400,0.345400,0.426800,0.201200,0.304000,0.097440,...,36.040000,49.540000,251.200000,4254.000000,0.222600,1.058000,1.252000,0.291000,0.663800,0.207500

## Table A

## Logistic Regression

In [34]:
lr=LogisticRegression(max_iter=5000)
lr.fit(X_train,y_train)
pred_lr=lr.predict(X_test)
print("Logistic Test Accuracy:",accuracy_score(y_test,pred_lr))
pred_lr_train=lr.predict(X_train)
print("Logistic Train Accuracy:",accuracy_score(y_train,pred_lr_train))

Logistic Test Accuracy: 0.9473684210526315
Logistic Train Accuracy: 0.9698492462311558

## Decision Tree

In [35]:
dt=DecisionTreeClassifier()
dt.fit(X_train,y_train)
pred_dt=dt.predict(X_test)
print("Logistic Test Accuracy:",accuracy_score(y_test,pred_dt))
pred_dt_train=dt.predict(X_train)
print("Logistic Train Accuracy:",accuracy_score(y_train,pred_dt_train))

Logistic Test Accuracy: 0.9239766081871345
Logistic Train Accuracy: 1.0

## KNN

In [36]:
knn=KNeighborsClassifier()
knn.fit(X_train,y_train)
pred_knn=knn.predict(X_test)
print("Logistic Test Accuracy:",accuracy_score(y_test,pred_knn))
pred_knn_train=knn.predict(X_train)
print("Logistic Train Accuracy:",accuracy_score(y_train,pred_knn_train))

Logistic Test Accuracy: 0.935672514619883
Logistic Train Accuracy: 0.9396984924623115

## Naive Bayes

In [37]:
nb=GaussianNB()
nb.fit(X_train,y_train)
pred_nb=nb.predict(X_test)
print("Logistic Test Accuracy:",accuracy_score(y_test,pred_nb))
pred_nb_train=nb.predict(X_train)
print("Logistic Train Accuracy:",accuracy_score(y_train,pred_nb_train))

Logistic Test Accuracy: 0.9298245614035088
Logistic Train Accuracy: 0.9472361809045227

## Neural Network

In [38]:
nn=MLPClassifier(max_iter=5000)
nn.fit(X_train,y_train)
pred_nn=nn.predict(X_test)
print("Logistic Test Accuracy:",accuracy_score(y_test,pred_nn))
pred_nn_train=nn.predict(X_train)
print("Logistic Train Accuracy:",accuracy_score(y_train,pred_nn_train))

Logistic Test Accuracy: 0.9473684210526315
Logistic Train Accuracy: 0.949748743718593

## PREDICTIONS

In [46]:
Precision = precision_score(y_test,pred_lr)
recall = recall_score(y_test,pred_lr)
f1 = f1_score(y_test, pred_lr)
roc = roc_auc_score(y_test, pred_lr)

print ("Logestic regression")
print ("precision :",Precision)
print ("recall :",recall)
print ("f1 :",f1)
print ("roc :",roc)

Logestic regression
precision : 0.9375
recall : 0.9813084112149533
f1 : 0.958904109589041
roc : 0.9359667056074766

In [49]:
Precision = precision_score(y_test,pred_dt)
recall = recall_score(y_test,pred_dt)
f1 = f1_score(y_test, pred_dt)
roc = roc_auc_score(y_test, pred_dt)

print ("Decision Tree")
print ("precision :",Precision)
print ("recall :",recall)
print ("f1 :",f1)
print ("roc :",roc)

Decision Tree
precision : 0.9272727272727272
recall : 0.9532710280373832
f1 : 0.9400921658986175
roc : 0.9141355140186915

In [50]:
Precision = precision_score(y_test,pred_knn)
recall = recall_score(y_test,pred_knn)
f1 = f1_score(y_test, pred_knn)
roc = roc_auc_score(y_test, pred_knn)

print ("KNN")
print ("precision :",Precision)
print ("recall :",recall)
print ("f1 :",f1)
print ("roc :",roc)

KNN
precision : 0.9363636363636364
recall : 0.9626168224299065
f1 : 0.9493087557603687
roc : 0.9266209112149533

In [54]:
Precision = precision_score(y_test,pred_nb)
recall = recall_score(y_test,pred_nb)
f1 = f1_score(y_test, pred_nb)
roc = roc_auc_score(y_test, pred_nb)

print ("Naive Bayes")
print ("precision :",Precision)
print ("recall :",recall)
print ("f1 :",f1)
print ("roc :",roc)

Naive Bayes
precision : 0.9130434782608695
recall : 0.9813084112149533
f1 : 0.9459459459459459
roc : 0.9125292056074765

In [53]:
Precision = precision_score(y_test,pred_nn)
recall = recall_score(y_test,pred_nn)
f1 = f1_score(y_test, pred_nn)
roc = roc_auc_score(y_test, pred_nn)

print ("Neural Network")
print ("precision :",Precision)
print ("recall :",recall)
print ("f1 :",f1)
print ("roc :",roc)

Neural Network
precision : 0.9375
recall : 0.9813084112149533
f1 : 0.958904109589041
roc : 0.9359667056074766

## Table B

## Logical Regression

In [59]:
cm_lr=confusion_matrix(y_test,pred_lr)
print("\nLogistic Regression Confusion Matrix:")
print(cm_lr)

TN1, FP1, FN1, TP1 = cm_lr.ravel()
type1_lr=FP1/(FP1+TN1)
type2_lr=FN1/(FN1+TP1)

print("FP Type1:",FP1)
print("FN Type2:",FN1)
print("Type1 Error rate:",type1_lr*100)
print("Type2 Error rate: ",type2_lr*100)

Logistic Regression Confusion Matrix:
[[ 57   7]
 [  2 105]]
FP Type1: 7
FN Type2: 2
Type1 Error rate: 10.9375
Type2 Error rate:  1.8691588785046727

## Decision Tree

In [ ]:
cm_dt=confusion_matrix(y_test,pred_dt)
print("\nDecision tree Confusion Matrix:")
print(cm_dt)

TN2, FP2, FN2, TP2 = cm_dt.ravel()
type1_dt=FP2/(FP2+TN2)
type2_dt=FN2/(FN2+TP2)

print("FP Type1:",FP2)
print("FN Type2:",FN2)
print("Type1 Error rate:",type1_dt*100)
print("Type2 Error rate: ",type2_dt*100)

## KNN

In [ ]:
cm_knn=confusion_matrix(y_test,pred_knn)
print("\nKNN Confusion Matrix:")
print(cm_knn)

TN3, FP3, FN3, TP3 = cm_knn.ravel()
type1_knn=FP3/(FP3+TN3)
type2_knn=FN3/(FN3+TP3)

print("FP Type1:",FP3)
print("FN Type2:",FN3)
print("Type1 Error rate:",type1_knn*100)
print("Type2 Error rate: ",type2_knn*100)

## Naive Bayes

In [58]:
cm_nb=confusion_matrix(y_test,pred_nb)
print("\nNaive Bayes Confusion Matrix:")
print(cm_nb)

TN4, FP4, FN4, TP4 = cm_nb.ravel()
type1_nb=FP4/(FP4+TN4)
type2_nb=FN4/(FN4+TP4)

print("FP Type1:",FP4)
print("FN Type2:",FN4)
print("Type1 Error rate:",type1_nb*100)
print("Type2 Error rate: ",type2_nb*100)

Precision : 0.9130434782608695
Recall: 0.9813084112149533
Fi-score : 0.958904109589041
ROC-AUC: 0.9359667056074766

## Neural Network

In [60]:
cm_nn=confusion_matrix(y_test,pred_nn)
print("\nNeural Network Confusion Matrix:")
print(cm_nn)

TN5, FP5, FN5, TP5 = cm_nn.ravel()
type1_nn=FP5/(FP5+TN5)
type2_nn=FN5/(FN5+TP5)

print("FP Type1:",FP5)
print("FN Type2:",FN5)
print("Type1 Error rate:",type1_nn*100)
print("Type2 Error rate: ",type2_nn*100)

Neural Network Confusion Matrix:
[[ 57   7]
 [  2 105]]
FP Type1: 7
FN Type2: 2
Type1 Error rate: 10.9375
Type2 Error rate:  1.8691588785046727